-- ============================================================
-- Ticketverse AFL Brownlow Draft Comp — Supabase schema
-- ============================================================

-- ---------- ENTRANTS ----------
create table entrants (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  pin text not null,                 -- 4-digit PIN, sent privately
  draft_position int not null unique, -- 1..N, generated by random draw
  created_at timestamptz default now()
);

-- ---------- AFL PLAYERS (master list, synced from data source) ----------
create table afl_players (
  id uuid primary key default gen_random_uuid(),
  full_name text not null,
  team text not null,
  team_short text,                    -- e.g. "COL", "CARL" for flag/badge lookup
  external_id text unique,            -- id from source API, for re-sync
  games_played_this_season int default 0,
  active boolean default true,        -- has played a game this season
  created_at timestamptz default now()
);

create index idx_afl_players_active on afl_players(active);

-- ---------- DRAFT CONFIG ----------
create table draft_config (
  id int primary key default 1,       -- singleton row
  total_rounds int not null default 10,
  num_entrants int not null default 12,
  current_round int not null default 1,
  current_pick_in_round int not null default 1, -- 1-indexed position within the round
  draft_status text not null default 'not_started', -- not_started | in_progress | complete
  round_multipliers jsonb not null default '{"1":1,"2":1,"3":1,"4":2,"5":2,"6":2,"7":2,"8":3,"9":3,"10":3}'
);

insert into draft_config (id) values (1);

-- ---------- PICKS ----------
create table picks (
  id uuid primary key default gen_random_uuid(),
  entrant_id uuid not null references entrants(id),
  afl_player_id uuid not null references afl_players(id) unique, -- a player can only be picked once, ever
  round int not null,
  pick_number int not null unique,     -- global sequence 1..(num_entrants*rounds), enforces draft order
  multiplier int not null,             -- copied from draft_config at time of pick
  created_at timestamptz default now(),
  unique (entrant_id, round)           -- one pick per entrant per round
);

create index idx_picks_entrant on picks(entrant_id);

-- ---------- BROWNLOW VOTES (entered live by admin on count night) ----------
create table brownlow_games (
  id uuid primary key default gen_random_uuid(),
  round_name text not null,            -- e.g. "Round 1", "Round 23"
  home_team text not null,
  away_team text not null,
  match_date date,
  votes_entered boolean default false,
  created_at timestamptz default now()
);

create table brownlow_votes (
  id uuid primary key default gen_random_uuid(),
  game_id uuid not null references brownlow_games(id),
  afl_player_id uuid not null references afl_players(id),
  votes int not null check (votes in (1,2,3)),
  created_at timestamptz default now(),
  unique (game_id, afl_player_id) -- a player can't get two vote entries in the same game
);

create index idx_votes_player on brownlow_votes(afl_player_id);

-- ---------- LIVE COUNT STATE (what "updated up to" the ladder should show) ----------
create table live_count_state (
  id int primary key default 1,
  updated_through_round text,          -- e.g. "Round 14" — display label only
  is_live boolean default false
);

insert into live_count_state (id) values (1);

-- ============================================================
-- VIEWS
-- ============================================================

-- Each entrant's total live points = sum(votes * pick.multiplier) for their picked players
create or replace view entrant_totals as
select
  e.id as entrant_id,
  e.name,
  coalesce(sum(bv.votes * p.multiplier), 0) as total_points
from entrants e
left join picks p on p.entrant_id = e.id
left join brownlow_votes bv on bv.afl_player_id = p.afl_player_id
group by e.id, e.name;

-- Draft board: static picks table, ordered by pick_number
create or replace view draft_board as
select
  p.pick_number,
  p.round,
  e.draft_position,
  e.name as entrant_name,
  ap.full_name as player_name,
  ap.team,
  p.multiplier
from picks p
join entrants e on e.id = p.entrant_id
join afl_players ap on ap.id = p.afl_player_id
order by p.pick_number;
